name: main_application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: install requirements
        run: python -m pip install ./code/requirements.txt
      - name: execute py script
        env: 
          NEO4J_CONNECTION_URI: ${{ secrets.NEO4J_CONNECTION_URI }}
          NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
        run: python ./code/app.py
