name: main_application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
#       - name: install requirements
#         run: python -m pip install -r ./code/requirements.txt
      - name: Set environment variables
        run: python -c 'import os;print(os.environ)'
        env: 
          NEO4J_CONNECTION_URI: ${{ secrets.NEO4J_CONNECTION_URI }}
          NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
#         run: python ./code/app.py
